const items = [
  {
    id: 1,
    foodname: 'Masala Dosa',
    imageLink: '',
    restaurant: 'Vidyarthi Bhavan',
    sourceLat: '12.9772',
    sourceLong: '77.5934',
    price: 150,
  },
  {
    id: 2,
    foodname: 'Butter Chicken',
    imageLink: '',
    restaurant: 'Punjab Grill',
    sourceLat: '12.9765',
    sourceLong: '77.5939',
    price: 320,
  },
  {
    id: 3,
    foodname: 'Bisi Bele Bath',
    imageLink: '',
    restaurant: "Maiya's",
    sourceLat: '12.9769',
    sourceLong: '77.5933',
    price: 180,
  },
  {
    id: 4,
    foodname: 'Hyderabadi Biryani',
    imageLink: '',
    restaurant: 'Meghana Foods',
    sourceLat: '12.9766',
    sourceLong: '77.5937',
    price: 280,
  },
  {
    id: 5,
    foodname: 'Pav Bhaji',
    imageLink: '',
    restaurant: 'Shiv Sagar',
    sourceLat: '12.9770',
    sourceLong: '77.5935',
    price: 160,
  },
  {
    id: 6,
    foodname: 'Idli Sambar',
    imageLink: '',
    restaurant: 'MTR',
    sourceLat: '12.9767',
    sourceLong: '77.5938',
    price: 120,
  },
  {
    id: 7,
    foodname: 'Paneer Tikka',
    imageLink: '',
    restaurant: 'Barbeque Nation',
    sourceLat: '12.9764',
    sourceLong: '77.5937',
    price: 250,
  },
  {
    id: 8,
    foodname: 'Mysore Pak',
    imageLink: '',
    restaurant: 'Sri Krishna Sweets',
    sourceLat: '12.9771',
    sourceLong: '77.5934',
    price: 200,
  },
  {
    id: 9,
    foodname: 'Fish Curry',
    imageLink: '',
    restaurant: 'Fishland',
    sourceLat: '12.9769',
    sourceLong: '77.5938',
    price: 300,
  },
  {
    id: 10,
    foodname: 'Gobi Manchurian',
    imageLink: '',
    restaurant: 'Beijing Bites',
    sourceLat: '12.9765',
    sourceLong: '77.5935',
    price: 180,
  },
  {
    id: 11,
    foodname: 'Ragi Mudde',
    imageLink: '',
    restaurant: 'Oota Bangalore',
    sourceLat: '12.9767',
    sourceLong: '77.5933',
    price: 150,
  },
  {
    id: 12,
    foodname: 'Chole Bhature',
    imageLink: '',
    restaurant: 'Punjabi Rasoi',
    sourceLat: '12.9770',
    sourceLong: '77.5939',
    price: 200,
  },
  {
    id: 13,
    foodname: 'Kesar Pista Kulfi',
    imageLink: '',
    restaurant: 'Corner House',
    sourceLat: '12.9772',
    sourceLong: '77.5936',
    price: 100,
  },
  {
    id: 14,
    foodname: 'Akki Roti',
    imageLink: '',
    restaurant: 'Hallimane',
    sourceLat: '12.9766',
    sourceLong: '77.5934',
    price: 120,
  },
  {
    id: 15,
    foodname: 'Medu Vada',
    imageLink: '',
    restaurant: 'Rameshwaram Cafe',
    sourceLat: '12.9764',
    sourceLong: '77.5938',
    price: 140,
  },
  {
    id: 16,
    foodname: 'Chilli Chicken',
    imageLink: '',
    restaurant: 'Mainland China',
    sourceLat: '12.9771',
    sourceLong: '77.5937',
    price: 220,
  },
  {
    id: 17,
    foodname: 'Mangalore Buns',
    imageLink: '',
    restaurant: 'Mangalore Pearl',
    sourceLat: '12.9768',
    sourceLong: '77.5935',
    price: 130,
  },
  {
    id: 18,
    foodname: 'Mushroom Masala',
    imageLink: '',
    restaurant: 'Rajdhani',
    sourceLat: '12.9765',
    sourceLong: '77.5933',
    price: 240,
  },
  {
    id: 19,
    foodname: 'Gulab Jamun',
    imageLink: '',
    restaurant: 'Anand Sweets',
    sourceLat: '12.9770',
    sourceLong: '77.5938',
    price: 160,
  },
  {
    id: 20,
    foodname: 'Thali',
    imageLink: '',
    restaurant: 'Nagarjuna',
    sourceLat: '12.9767',
    sourceLong: '77.5934',
    price: 350,
  },
];

export default items;
